export enum TYPES {
  SET_TODOS = "SET_TODOS",
  ADD_TODO = "ADD_TODO",
  REMOVE_TODO = "REMOVE_TODO",
  FETCH_TODO = "FETCH_TODO",
  COMPLETE_TODO = "COMPLETE_TODO",
  LOADER_ON = "LOADER_ON",
  LOADER_OFF = "LOADER_OFF",
  ERROR_ON = "ERROR_ON",
  ERROR_OFF = "ERROR_OFF",
}
